lit/lit-element

demo/lit-element.html
package.json
src/@polymer/lit-element.ts
src/@polymer/test/lit-element_test.ts

Fixes https://github.com/PolymerLabs/lit-element/issues/5
* changes `nextRendered` promise to `renderComplete`
* alters render so that it's called within `_propertiesChanged`
* adds render helpers: `renderAttributes`, `classString`, `styleString`

Add `didRender` method 

---

package-lock.json
package.json
src/@polymer/lit-element.ts
src/@polymer/test/lit-element_test.ts

Fixes #18 
Allows users to specify a render target which defaults to the element shadowRoot. Just return `this` to render into the elements childNodes.
Also improves console warning describing that properties are set re-entrantly. Stack trace should now better help identify offending code.

Adds _createRoot method

---

.gitignore
tsconfig.json

it seems as if it wont compile correctly if you have `"modules": "not commonjs"`, so you have to specify to resolve modules with `"moduleResolution": "commonjs"` to make it compile yet output es2015 modules

Make ts compilable

---

README.md

This PR fixes `PropertiesMixin` link from `properties-mixin.html` to `properties-mixin.js`.

chore(README.md): properties-mixin.html -> properties-mixin.js

---

src/lit-element.ts

This also exports the `svg` template literal as defined in https://github.com/Polymer/lit-html/blob/1dc43255d172f412fd19784c190764d05605cc16/src/lib/lit-extended.ts#L25-L29
Fixes #56

Export svg template literal from lit-extended

---

src/lit-element.ts
src/test/lit-element_test.ts
tslint.json

TSLint was actually never doing anything, because the `tslint.json` was missing. I adopted the configuration of Polymer/tools (https://github.com/Polymer/tools/blob/master/tslint.json) and fixed the corresponding issues. We were missing semicolons and `any` types. I also ran the formatter again, as some of the type definitions were getting quite long.

Fix TSLint by adding configuration and fix style errors

---

README.md

Add JSFiddle to list of getting started examples.
JSFiddle is often the online editor of choice for StackOverflow examples and help.

Add JSFiddle example

---

package-lock.json
package.json
src/lit-element.ts
src/test/lit-element_styling_test.ts
src/test/lit-element_test.ts
test/runner.html

Fixes #34 and #39.
* ensure `ShadyCSS.styleElement` is called when element is connected
* adds styling tests
* works with lit-html's updated shady-render implementation (https://github.com/Polymer/lit-html/pull/337)
* also makes `requestRender` public

Improve ShadyCSS integration

---

src/lit-element.ts
src/test/lit-element_test.ts

LitElement warns when properties are changed as a result of property changes. That's all well and good, but the way it goes about it is disruptive. Instead of using the standard `console.warn`, LitElement logs a `console.trace`. This can be really annoying at times, as it fills up the console with  information which may not be immediately relevant. A console warning, which is in any event preferred for this type of message, will also print the trace, but collapsed behind a drill-down control, and should be used instead.
Example:
Developer has some improper data flow which causes this warning to log. However, it's not causing UX problems, so she's de-prioritized that for now. However, an important UI bug has come up and she needs to log information to the console to fix it. In this case, …

Changes properties change trace to warning

---

README.md
src/lib/updating-element.ts
src/lit-element.ts
src/test/lit-element_styling_test.ts
src/test/lit-element_test.ts

**Adds**
* `updated`: called after the element updates and used to directly manipulate element DOM, for example focusing an element. Previously this code was written in `update` after calling `super.update`.
**Changes**
* `firstUpdated`: This was previously `firstRendered` and was changed to expose only one entry point using the "render" terminology.
* `requestUpdate`: This was previously `invalidate` and `invalidateProperty`. This one method now does double duty and was changed so we consistently use the "update" concept.
* `hasChanged`: This was previously `shouldInvalidate` and was changed to indicate meaning rather than what action is taken as a result.

Update lifecycle based on feedback

---

README.md
src/lib/updating-element.ts

Documentation typo fixes and clarifications

---

README.md
package-lock.json
package.json
src/lib/updating-element.ts
src/test/lit-element_test.ts

Fixes #180
Changes test and documents limitation. Older versions of Chrome/Safari may not have element constructor default values for native platform properties (e.g. `id`).

Address native properties issue on older browsers

---

src/lib/updating-element.ts
src/test/lit-element_test.ts

Fix #172
As described in #172, the `firstUpdated` lifecycle method is not always called. 
The problem was in the `_validate()` method of `lib/update-element.ts`:
```TypeScript
private _validate() {
// Mixin instance properties once, if they exist.
if (this._instanceProperties) {
this._applyInstanceProperties();
}
if (this.shouldUpdate(this._changedProperties)) {
const changedProperties = this._changedProperties;
this.update(changedProperties);
const needsFirstUpdate = !(this._updateState & STATE_HAS_UPDATED);
this._markUpdated();
if (needsFirstUpdate) {
this.firstUpdated(changedProperties);
}
this.updated(changedProperties);
} else {
this._markUpdated();
}
}
private _markUpdated() {
this._changedProperties = new Map();
this._updateState = this._updateState & ~STATE_UPDATE_REQUESTED | …
```

Ensure `firstUpdated` is always called when the element first updated

---

CHANGELOG.md
src/lib/decorators.ts
src/test/lib/decorators_test.ts
test/runner.html

Add @query, @queryAll and @customElement decorators

---

CHANGELOG.md
README.md
src/lit-element.ts

This makes it easier to write types in TypeScript when using the JavasScript mixin pattern, e.g.
```(base) => class extends base {...}```
This change makes implementing the `render` method optional.

LitElement is no longer an abstract class

---

src/lib/updating-element.ts

While this type can be inferred in most cases, it would be useful to export it for places where we want a strongly typed serializer which isn't part of the properties map (yet).
would this be fine?

export attribute deserializer interface

---

README.md

In the Declarative Rendering section of README.md it seems to be using lit-html syntax rather than how we use properties in LitElement where we'd need to specify the 'this' keyword?
So rather than:
class="${color} special"
we should have
class="${**this**.color} special"
Fixes #197

Update property syntax in README.md 

---

README.md

Readme was missing an example for setting boolean attributes. Added the same example that is used in the lit-html documentation.

Add syntax example for boolean attributes

---

README.md

I was trying to find the documentation for the lit-html API for how to write templates but had some problems finding it. I suspect I'm not alone, so I added a sentence and a link to the lit-html guide to make it easier to find.

Added reference to lit-html guide for how to create templates

---

src/lit-element.ts

This way, an overriding class will get a type error if their render function returns something that isn't a TemplateResult.

Explicitly annotate render's return type

---

src/lib/updating-element.ts
src/lit-element.ts

Currently, compiling lit-element with the Closure compiler results in a
clean build but a number of hard JS errors due to a few issues:
- static methods being collapsed (i.e. removed entirely)
- Object.hasOwnPropertyName() looking for static properties that have
been rewritten by the compiler
- static property initializers not being run when @exported
The last issue is a compiler bug being tracked internally, but all three
need to be worked around before this will compile and run cleanly.
This includes all of the necessary fixes, including addressing the last
issue by moving the Object.hasOwnPropertyName('_classProperties') check
to _finalize(). This is necessary to ensure that _classProperties is
defined before it's iterated in observedProperties on an element that
has no properties. …

Fully support Closure compiler including ADVANCED_OPTIMIZATIONS

---

.gitignore
tsconfig.json

This makes go to definition take users of the module go to the correct
file in src/ in their editor.
Same as Polymer/lit-html#528

Enable TypeScript declaration maps

---

CHANGELOG.md
demo/lit-element.html
package-lock.json
package.json
src/env.d.ts
src/lib/css-tag.ts
src/lib/updating-element.ts
src/lit-element.ts
src/test/lit-element_styling_test.ts

Fixes #391.
This should be implemented to return an array of styles defined using the `css` tag function. These styles will be applied with `adoptedStyleSheets` where available and shimmed when not.

Adds `static get styles()`

---

src/lit-element.ts

This should close #412. In short since `render` returns returns `TemplateResult | void` since #316 was merged, it is impossible to add a type definition other than `any` to the return type of `render()` method unless you have `lit-html` installed as well. This PR aims to solve this problem by exporting `TemplateResult` along side `html, svg`.

Added TemplateResult to exports

---

package-lock.json
src/env.d.ts
src/lib/decorators.ts

Fixes: #428 
Verified by pushing 2.0.0-dev.ff4fefd to npm and building PWA Starter Kit

Fix decorator types causing compiler errors for TypeScript users.

---

src/lib/decorators.ts

This was the only error that came up when compiling lit-element with typed tsickle output!

Suppress jscompiler visibility error.

---

src/lit-element.ts
src/test/lit-element_styling_test.ts
tsconfig.json

Fixes https://github.com/Polymer/lit-element/issues/429
Flattens styles array before deduplication. 
Recursive types are a bit funky, I had to use an interface as instructed here: https://github.com/unional/typescript-guidelines/blob/master/pages/advance-types/recursive-types.md
I'm using Array.prototype.flat when supported, otherwise there is a minimal implementation. 
I had to enable esnext typings for Array.prototype.flat support.

Flatten styles array

---

src/lib/decorators.ts
src/lib/updating-element.ts

This makes the code safe against being compiled with non-spec-compliant for/of, which will usually expect an array. Previously properties would silently not work when compiled with Babel on many online code editor platforms.

Replace use of for/of loops over Maps with forEach.

---

CHANGELOG.md
src/lib/decorators.ts
src/lib/updating-element.ts
src/test/lib/decorators_test.ts
src/test/lib/updating-element_test.ts

Fixes #450. This removes all wrapping of existing accessors. This changes makes property generation simpler and more straightforward. If an accessor should not be generated, for example when there is a user defined accessor, users should set the `noAccessor` flag to true.

Removes wrapping of properties in favor of always respecting `noAccessor`

---

CHANGELOG.md
src/lib/updating-element.ts
src/lit-element.ts
src/test/lit-element_styling_test.ts
tsconfig.json

Fixes #452.
In addition...
* Fixes type settings so `Array.flat` works.
* Optimization: ensures `this.styles` is accessed only once per definition. Since this getter generates CSSResults, it should not be run superfluously.

Removes default for `static get styles`

---

CHANGELOG.md
src/lib/updating-element.ts
src/lit-element.ts

JSCompiler_renameProperty can't be exported from a module, it's a global. If it's exported then jscompiler doesn't treat it as special, it's just a normal function.

Fix closure compiler renaming safety.

---

CHANGELOG.md
src/lib/css-tag.ts
src/test/lit-element_styling_test.ts

Fixes #451 and #471. Non-literal values can now be included in styling with `css` by using the `unsafeCss` function. This is named "unsafe" so users know this they must use this carefully to avoid security issues.

Adds `unsafeCss` for composing values into `css`

---

CHANGELOG.md
src/lit-element.ts
src/test/lit-element_styling_test.ts

Fixes #480 by refactoring to avoid the typo that was causing styling to be duplicated when an array was returned from `static get styles`.

Ensure styles are not duplicated in ShadowDOM

---

docs/_guide/styles.md
docs/_includes/projects/docs/style/bestpracs/my-element.js
docs/_includes/projects/docs/style/customproperties/my-element.js
docs/_includes/projects/docs/style/host/my-element.js
docs/_includes/projects/docs/style/hostselector/my-element.js
docs/_includes/projects/docs/style/inherited/my-element.js
docs/_includes/projects/docs/style/maindocument/my-element.js
docs/_includes/projects/docs/style/slotted/my-element.js
docs/_includes/projects/docs/style/smalltheme/my-element.js

I had some trouble getting the attribute `hidden` to work, because the examples in the docs are faulty.
* I fixed the code snippets / examples.
* I changed the explanatory introduction text, to point out that there are two pseudo-classes, how they are different, and which one to use when.
Fixes part of #353.

Fix documentation of :host and :host() pseudo-classes

---

docs/index.md

"Made to share" and "Interoperable" seemed redundant. Fast/light is most valuable to users. Standards seems like #2.

[docs] Reorder the sections in Why use LitElement

---

docs/_guide/properties.md
docs/_includes/projects/properties/customsetter/my-element.js

no Issues
I found typos in docs :eyes:

[docs] Fix option name of `noAccessor`

---

src/lib/decorators.ts

Removed comment about HTMLElementTagNameMap for customElement decorator as this was changed to be a string in #291 . Thanks for spotting @katejeffreys.
#291

Removed comment about HTMLElementTagNameMap for customElement decorator

---

CONTRIBUTING.md
README.md

Fixes #514 
* removes inline docs and points to web site docs
* refines examples

Simplify Readme

---

CHANGELOG.md
src/lib/css-tag.ts

Fixes #525.
Adds a check intended to ensure that `CSSStyleSheet` is constructable.

Fix for incorrect implementation of `adoptedStylesheets`

---

src/lib/css-tag.ts
src/test/lit-element_styling_test.ts

Adds `toString` to CSSResult

---

docs/_data/guide.yml
docs/_guide/events.md
docs/_includes/projects/events/child/index.html
docs/_includes/projects/events/child/index.ts
docs/_includes/projects/events/child/manifest.json
docs/_includes/projects/events/child/my-element.js
docs/_includes/projects/events/childimperative/index.html
docs/_includes/projects/events/childimperative/index.ts
docs/_includes/projects/events/childimperative/manifest.json
docs/_includes/projects/events/childimperative/my-element.js
docs/_includes/projects/events/events/index.html
docs/_includes/projects/events/events/index.ts
docs/_includes/projects/events/events/manifest.json
docs/_includes/projects/events/events/my-element.js
docs/_includes/projects/events/host/index.html
docs/_includes/projects/events/host/index.ts
docs/_includes/projects/events/host/manifest.json
docs/_includes/projects/events/host/my-element.js

needs work 
staged https://20190108t174118-dot-polymer-lit-element.appspot.com/guide/events 
fixes #371
fixes #139

[docs] Draft events docs ready for review

---

.clang-format
src/demo/ts-element.ts
src/env.d.ts
src/lib/css-tag.ts
src/lib/decorators.ts
src/lib/updating-element.ts
src/lit-element.ts
src/test/lib/decorators_test.ts
src/test/lib/updating-element_test.ts
src/test/lit-element_styling_test.ts
src/test/lit-element_test.ts
src/test/test-helpers.ts

Add version global

---

src/lib/decorators.ts
src/lib/updating-element.ts
src/lit-element.ts
src/test/lib/decorators_test.ts
src/test/lib/updating-element_test.ts
src/test/lit-element_styling_test.ts
src/test/lit-element_test.ts
tsconfig.json
tslint.json

Also marks any properties that seem readonly as `readonly`. Likewise `ReadonlyArray`.

Remove almost all uses of `any`.

---

README.md

Fixes the `customElement` decorator usage on the overview example.

Remove semicolon from customElement decorator on README example

---

CHANGELOG.md
src/lib/decorators.ts
src/lit-element.ts

This tells https://github.com/angular/tsickle to add Closure JS Compiler @export annotations to properties annotated with the `query` and `queryAll` decorators. We already did this for property and other decorators, but we also need it for these (due to the way that TypeScript generates decorator code which involves a static string of the property name).
Also makes `LitElement.renderRoot` `public readonly` instead of `protected` because the decorators need to access that property. Presumably this problem did not come up before because tsickle was not producing as correct types for Closure JS Compiler as it is now (maybe it doesn't understand the additional indirection we had before).

Add @ExportDecoratedItems annotations to query and queryAll decorators.

---

docs/_try/create.md

It should include `after/my-element.js`, not `before/my-element.js`

[docs] Fix my-element.js for the completed code

---

docs/_guide/styles.md

`:host([.important])` doesn't match anything. This should either be an attribute selector:
`:host([important])` matches `<my-element important>`
Or a class selector:
`:host(.important)` matches `<my-element class="important">`

Fix syntax

---

docs/_api/api-readme.md

Since stable `lit-element` has already been released so `in development` status should be removed.

remove in development status from api-readme

---

docs/_guide/index.md

Feedback was that this is confusing - removing it

Remove "Quick Start" section from Introduction

---

src/lib/css-tag.ts

Typescript uses the lowercase `string` type, not the `String` class.
Per https://github.com/Polymer/lit-element/pull/508#discussion_r254383556

Fix cssResult.toString type

---

src/lit-element.ts

I was experimenting with [import maps](https://github.com/WICG/import-maps) in Chrome Canary. It won't be really useful for us until https://crbug.com/928149 (and, practically speaking) https://crbug.com/928149 are implemented, but it's at a really promising state!
This change ensures that when we're importing a file within another package, we give the full filename.

Add file extensions fo imports where missing.

---

src/lib/decorators.ts
src/lib/updating-element.ts
src/lit-element.ts
src/test/lib/decorators_test.ts
src/test/lit-element_styling_test.ts
tslint.json

This is the result of turning on the no-unnecessary-type-assertion tslint pass and running `--fix`. There was one place where I disabled this pass where we needed `!` to note that a variable was definitely  assigned to before it was read.
I like this lint pass because it makes the code a bit easier to read and understand. I will admit though that I'm proposing this change because we use this lint pass downstream, and it's annoying seeing the lint warnings.

Remove unnecessary type assertions

---

CHANGELOG.md
src/lib/updating-element.ts
src/test/lib/updating-element_test.ts

Fixes #592. Ensures a reflecting property set immediately after a corresponding attribute reflects correctly.

Ensure attribute reflected from property is correct

---

CHANGELOG.md
src/lib/updating-element.ts
src/test/lib/updating-element_test.ts

Fixes #594. Ensures an early access of `updateComplete` will not complete before the element has first updated (at connection time).

Schedules `requestUpdate` in `initialize` rather than `connectedCallback`

---

CHANGELOG.md
src/lib/updating-element.ts
src/test/lib/updating-element_test.ts
src/test/lit-element_test.ts

Fixes #262.
Catch exceptions during update and ensure the element marks itself as finished updating.
Note, this change also ensures the `updateComplete` promise is rejected if there's an exception during update.

Handle exceptions during update so that they do not break subsequent updates

---

docs/_guide/lifecycle.md

This corrects the format of a intra-docs link, fixing #587 and #510 alongside #517. #517 provides the relevant anchor, this patch should cause this link to resolve to that section (instead of 404ing)

Update Lifecycle doc's broken link to Properties

---

docs/_guide/templates.md

The example snippets in the section on *named slots* where showing the code for a `<stack-blitz>` custom element instead of displaying the example code.
I figured, this was probably a copy & paste glitch (from duplicating a "launch code editor" button), that even I might be able to solve.
Solves part of issue #352, precisely [this part](https://github.com/Polymer/lit-element/issues/352#issuecomment-446773772).

docs: fix included code snippets for named slots in templates

---

docs/_guide/templates.md

This is a draft of a fix for #506. It does add an advanced features section which says how to use lit-html and LitElement together. The link is just to the source code as apparently those docs are not live yet. 
@katejeffreys Is it intentional that lit-html is not really mentioned on this page? It feels like this page duplicates some parts of the lit-html documentation while never mentioning lit-html once. I would probably mention once that `html`is a lit-html function and that the syntax is the same and under the hood LitElement uses lit-html to render the template. 
Also `nothing` does not seem to be mentioned in the lit-html documentation, will open an issue for it.

[docs] Add information about lit-html features in template syntax

---

docs/css/main.css

Fixes #635. Don't see a reason why `z-index: -1` needs to be there.
Staged at https://20190328t150824-dot-polymer-lit-element.appspot.com/guide/styles

[docs] Remove z-index on alert style

---

CHANGELOG.md
src/lib/css-tag.ts
src/test/lit-element_styling_test.ts

This allows for real JavaScript numbers within the css tagged template literal.
closes: #488

feat: allow JavaScript numbers in css template literal

---

docs/_guide/styles.md

This extra `</div>` is visible in the public docs here:
https://lit-element.polymer-project.org/guide/styles
Probably an artifact from an old `<div class="alert alert-info">`?

removing unnecessary closing div tag

---

src/lib/css-tag.ts
src/lib/decorators.ts
src/lib/updating-element.ts
src/lit-element.ts
src/test/lib/updating-element_test.ts
src/test/lit-element_test.ts
tslint.json

Because of https://github.com/google/closure-compiler/issues/3340 – `this` has an unknown type to closure compiler in static methods. In order to be compatible with the Closure Compiler + JSConformance `BanUnknownThis` check, we must explicitly add type annotations wherever we access `this` in a static method.
Yes, this is pretty awful from a legibility perspective. We could improve legibility at the cost of additional size by doing:
```typescript
const self = this as typeof LitElement;
```
I went with the zero-size-cost option here.

Add ugly type assertions for `this`

---

docs/_guide/styles.md

Updates style guide by removing reference to cssLiteral (previously removed) for using expressions in static styles with unsafeCSS method.

Replaces cssLiteral (removed) with unsafeCSS 

---

CONTRIBUTING.md

Google+ has been retired for non G Suite accounts.

Remove Google+ link

---

src/lib/updating-element.ts
src/lit-element.ts
tslint.json

This undoes f552fc47b12bf3e272aaeafe03d9d73bc4fff1f5 now that https://github.com/google/closure-compiler/issues/3340 has been fixed.

Remove ugly type assertions for `this`

---

docs/_guide/templates.md

Arrow function expressions without bodies shouldn't have semicolons, it's a parse error.
Reported by Vladimir K

Typo: remove semicolon

---

CHANGELOG.md
check-version-tracker.js
package-lock.json
package.json
src/lib/updating-element.ts
src/lit-element.ts

Also:
- Add a script that checks that lit-element.ts contains the latest version, to help ensure our tracker is current before publishing, and run in `prepublishOnly`.
- Add `npm run lint && npm test` to `prepublishOnly`.
- Remove `build` from `prepublishOnly` script, because it's already in `prepare`, which runs before `prepublishOnly`.
- Run clang-format.

Release lit-element 2.2.0

---

package-lock.json
package.json

clang-format is used in the 'format' script but isn't included in the dependencies.

Add 'clang-format' as a dev dependency.

---

CHANGELOG.md
src/lib/updating-element.ts
src/lit-element.ts

Fixes https://github.com/Polymer/lit-element/issues/732

Fix compatibility with JSC static property optimizations

---

docs/_guide/publish.md

`tsconfig.json` does not accept a value of `"es2017"` for `module`. Its schema also specifies allowed values in all
lowercase, so `es2015` is valid but `ES2015` is invalid (though the latter is accepted by the runtime).
Fixes #574.

Fix TypeScript configuration in publish docs

---

CHANGELOG.md
src/lib/updating-element.ts

When the target language is ES5, TypeScript does not support calling a superclass getter, which means it is not possible (or at least very awkward) to override the `updateComplete` getter in an element (because a call like `super.updateComplete.then(...)` will not compile). See https://github.com/microsoft/TypeScript/issues/338.
We now delegate the `updateComplete` getter to a new `_getUpdateComplete` method, which can be safely overriden by users. A little awkward, but seemed like the least bad solution we could think of.
See also https://github.com/material-components/material-components-web-components/pull/207 which tried to work around this issue.

Delegate updateComplete getter to getUpdateComplete method for TS ES5

---

src/lib/decorators.ts

The `@ExportDecoratedItems` annotation is required to instruct https://github.com/angular/tsickle to add an `@export` annotation for Closure.
The `@export` annotation is required because TypeScript's polyfilled decorator output is not compatible with Closure property renaming optimizations (since it passes the property name as a string).
Also, decorators must be declared as regular functions, not arrow functions, because the part of tsickle that recognizes decorators does not currently expect them to be defined as arrow functions.

Make eventOptions decorator compatible with tsickle/Closure compiler

---

docs/_guide/properties.md
docs/_includes/projects/properties/declaretypescript/my-element.ts

This adds an example to the properties guide that for custom accessors the `@property` decorator can be put on the getter. Closes #519.

Adds documentation on how to use custom accessors with  @property decorator

---

package-lock.json
package.json
src/lib/updating-element.ts
src/lit-element.ts

* Use _updateComplete Promise to wait for first connection
* Optimize _enqueueUpdate for size a bit
* Inline _markUpdated
* Inline and combine style flattening and de-duplication
Before:
```
┌─────────────────────────────────────────┐
│                                         │
│   Destination: lit-element.bundled.js   │
│   Bundle Size:  21.04 KB                │
│   Minified and Gzipped Size:  6.75 KB   │
│   Brothli size: 6.13 KB                 │
│                                         │
└─────────────────────────────────────────┘
```
After:
```
┌─────────────────────────────────────────┐
│                                         │
│   Destination: lit-element.bundled.js   │
│   Bundle Size:  20.7 KB                 │
│   Minified and Gzipped Size:  6.65 KB   │
│   Brothli size: …
```

A couple of small size optimizations

---

docs/_guide/templates.md
docs/_includes/projects/docs/templates/databinding/my-element.js

This removes the `?checked` reference in the docs in favor of `?disabled`, since this is a cleaner representation of a boolean attribute since there are no user interactions that can set the property.

Update doc references for ?checked

---

docs/_guide/use.md

The Open Web Components __developing server__ is now __ES dev server__
https://open-wc.org/developing/es-dev-server.html

Fix broken link to ES dev server

---

docs/css/main.css

Set z-index on side-nav style to prevent it from overlapping with the alert style in small screen devices

[Docs site] Add z-index on side-nav style

---

src/lib/updating-element.ts

Fixes #744
Add _optional_ use of generics on `PropertyValues` to allow Typescript to type-check/hint within the `firstUpdated` and `updated` methods. Because using the generics is optional, this is not a braking change.
To reiterate what I described in the issue initially: 
**Pros**
- It's opt-in.
- It's backwards compatible with the current definition.
- `props.has('unknownProp')` wouldn't type-check when using `PropertyValues<this>`.
- `props.has('notAnAtProp')` wouldn't type-check when using `PropertyValues<ImplementedInterface>` (see usage example below).
**Cons**
- People may expect `PropertyValues<this>` to infer and type-check `@properties`, even though the expected behavior is that it won't until applying `PropertyValues<ImplementedInterface>`.
All examples of current usage of …

Add optional use of generics on PropertyValues

---

src/lib/decorators.ts

Fixes https://github.com/Polymer/lit-element/issues/803
`customElement` wasn't rendering `@example` for some reason so it's just part of the description.

Add decorator examples

---

.travis.yml
CHANGELOG.md
src/lib/decorators.ts
src/lib/updating-element.ts
src/lit-element.ts
src/test/lib/decorators_test.ts
src/test/lit-element_styling_test.ts

By moving style gathering to initialization, stylesheets will only be
created for elements that have booted, and not for elements that have
only be registered.
This should be performance positive for applications with less than
ideal loading behaviors.
Fixes #870

Move style gathering from class finalization to initialization

---

CHANGELOG.md
src/lit-element.ts
src/test/lit-element_test.ts

- #712 Introduced a breaking behavior change for situations where
`render` is unimplemented, and DOM is added before being connected to
the document.

Only call lit-html render if LitElement subclass implements render

---

CHANGELOG.md
src/demo/ts-element.ts
src/lib/updating-element.ts
src/test/lib/updating-element_test.ts

Fixes #911. It is now easier to override property accessor creation. A new static `getPropertyDescriptor(name: PropertyKey, key: string|symbol, options: PropertyDeclaraction)` is added here. This method should return a [property descriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to use when defining the property. If no descriptor is returned, the property will not become an accessor.
Example:
```
class MyElement extends LitElement {
static getPropertyDescriptor(
name: PropertyKey,
key: string|symbol,
options: PropertyDeclaration) {
const defaultDescriptor = super.getPropertyDescriptor(name, key, options); 
const setter = defaultDescriptor.set;
return Object.assign(descriptor, {
set(this: MyElement, value: unknown) { …
```

Makes `createProperty` easier to use to customize properties

---

src/lib/updating-element.ts

Upstreams a change needed for internal closure compilation.

Add extra type information to help closure with type of static property.

---

src/lib/updating-element.ts

Static properties must use `@nocollapse`.

Fix static property for closure

---

src/lib/updating-element.ts
src/test/lib/updating-element_test.ts

Fixes #928. Also add tests that type custom property options in a variety of ways.

Removes index signature from PropertyDeclaration

---

src/lib/css-tag.ts
src/lit-element.ts
src/test/lit-element_styling_test.ts

Fixes #774. Supports native `CSSStyleSheet` if and only if native adopted style sheets on shadow roots are supported.

Native cssstylesheet

---

docs/_includes/project.html
docs/_layouts/default.html
docs/css/main.css
docs/package-lock.json
docs/package.json
docs/rollup.config.js
docs/src/babel-polyfills-nomodule.js

Fixes #970. Replaces deprecated Polymer CLI with rollup build.
Also ensures that something is displayed in place of the stack-blitz buttons when they fail to load.
Staged here:  https://rollup-test-dot-polymer-lit-element.uk.r.appspot.com/try
On that page, you'll see a 'LAUNCH CODE EDITOR' button. If that button's working, the JavaScript bundle has loaded correctly. (If you load the site in IE or disable JavaScript, you should see a grayed-out button that says, "Code editor not supported in this browser" or words to that effect.)

Use Rollup for build

---

docs/_guide/start.md

New draft getting started doc. Staged at:
https://new-getting-started-dot-polymer-lit-element.appspot.com
Leaving this PR open for feedback until Friday, 4/24.

New getting started doc

---

CHANGELOG.md
src/lib/updating-element.ts

* pass property options in default setter to avoid the map lookup
* move property initialization from constructor to initialize to provide additional control over construction

Micro-opt property sets and refactor initialization

---

docs/_guide/index.md

"PWA Starter Kit" is no longer under development, therefore I suggest to not link to it.
"lit-element-starter-ts" and "lit-element-starter-js" appear to be the new recommended starter projects. However, they are alredy linked on the getting started page.
Fixes #988

remove link to PWA Starter Kit

---

package.json
src/lib/css-tag.ts
src/lib/decorators.ts
src/lib/updating-element.ts
src/test/lib/decorators_test.ts
src/test/lib/updating-element_test.ts
src/test/lit-element_styling_test.ts

Fix queryAssignedNodes when unnamed slot is not first

---

docs/_layouts/default.html

Fixes #1006 (at least, the part of it that's a fixable bug).
Sets the copyright date to 2018-_current year when the site was built_. Should be accurate unless we rebuild the docs site in new year without making any changes to it. I'm willing to live with that.
Staged: https://20200527t134714-dot-polymer-lit-element.uk.r.appspot.com

Update copyright dates.

---

docs/_guide/events.md
docs/_guide/templates.md
docs/_includes/projects/docs/templates/compose/my-page.js

Decorator docs part 2/2.
Follow-on to #999.
Fixes #886.
Staged as: https://decorator-docs-2-dot-polymer-lit-element.uk.r.appspot.com
(Note that this branch doesn't include the new decorators chapter--that's in #999--so the links to that chapter are broken in the staging link above.)

Add decorators to events, templates chapters.

---

package-lock.json
package.json

Update downlevel-dts and make sure we don't nest ts3.4 typings folders.

---

README.md

@usergenic added this in 2018, and I reviewed, but I don't recall what our usage of Browserstack was. Something is misconfigured not and the badge displays a 404, so lets remove it for now before we publish 2.4.0 and get this readme with the broken badge on npm.

Remove browserstack badge from README

---

docs/_guide/build.md

Renames the "Compilers" section of the build guide to "TypeScript" and adds more actionable recommendations for how to deal with TypeScript.
Staged: https://typescript-build-dot-polymer-lit-element.uk.r.appspot.com/guide/build#typescript
This is a pretty small change. Tagging @rictic as the TS expert, but I think one review will do here.

Update TypeScript build info.

---

docs/api/classes/_lib_updating_element_.updatingelement.html
docs/api/classes/_lit_element_.cssresult.html
docs/api/classes/_lit_element_.litelement.html
docs/api/classes/_lit_element_.updatingelement.html
docs/api/interfaces/_lib_updating_element_.complexattributeconverter.html
docs/api/interfaces/_lib_updating_element_.haschanged.html
docs/api/interfaces/_lib_updating_element_.propertydeclaration.html
docs/api/interfaces/_lit_element_.complexattributeconverter.html
docs/api/interfaces/_lit_element_.haschanged.html
docs/api/interfaces/_lit_element_.internalpropertydeclaration.html
docs/api/interfaces/_lit_element_.propertydeclaration.html
docs/api/modules/_lib_updating_element_.html
docs/api/modules/_lit_element_.html

Regenerated API docs at HEAD. As far as I can see, this just updates the source code links.

Update API docs for 2.4.0.

---

docs/_guide/start.md

Fixes the "Rename your component" section, where the "build" step was not identified as TypeScript-only.

Fix typo, clarify step. Related to #1065.

---

src/lib/updating-element.ts

This makes this repo compliant with Bazel's TypeScript rules: https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsetse/rules/must_type_assert_json_parse_rule.ts

Add type assertion to JSON.parse().

---

docs/_guide/properties.md

This fixes a typo I noticed in the documentation.

Fix "not not" typo

---

CHANGELOG.md
src/lit-element.ts
src/test/lit-element_test.ts

This is a slightly simpler alternative for customizing shadow root options than implementing `createRenderRoot`.
Fixes #1147.

Adds `shadowRootOptions` feature

---

src/lit-element.ts

Static fields must be annotated with `@nocollapse` to get proper semantics -.-

Add @nocollapse to shadowRootOptions

---

src/lit-element.ts

This PR backports the `CSSResultGroup` type from `ReactiveElement`:
https://github.com/Polymer/lit-html/blob/664fbfb097712709de19a2a26d3caf89239ac723/packages/reactive-element/src/css-tag.ts#L22

lit-next forward-compat: Backport `CSSResultGroup` type.

---

README.md

Leading indentation inside fenced code blocks appears inside the rendered code blocks, rather than being removed like in 4-space-indented code blocks.

Remove leading indentation from README code snippets.

---

src/lib/decorators.ts

Fixes #1191
Some tools seemed to be copying the `@deprecated` annotation on `@internalProperty()` to `@state()`, presumably because of the assignment. Hopefully calling `internalProperty()` will avoid this. I checked in VS Code and it fixes that at least.

Make @state() not appear to be deprecated.

---

docs/css/main.css

From this:
To this:
a11y contrast checker shows that it's the same a11y rating - there were already problems with blue on white and the rating is not degraded with this bg

feat: make banner more apparent

---

docs/_guide/build.md
docs/_guide/community.md
docs/_guide/decorators.md
docs/_guide/events.md
docs/_guide/index.md
docs/_guide/lifecycle.md
docs/_guide/properties.md
docs/_guide/publish.md
docs/_guide/start.md
docs/_guide/styles.md
docs/_guide/templates.md
docs/_guide/use.md
docs/_includes/version-banner.html

Related to https://github,com/lit/lit.dev/issues/471
Staged: https://lit-dev-links-dot-polymer-lit-element.uk.r.appspot.com/guide
Also updated text a bit:

Add deep links to lit.dev equivalent pages.
