custom_typings/polymer.d.ts, package-lock.json, package.json, src/lit-element.ts, src/test/lit-element_test.ts, tsconfig.json
This also removes some weird folder structure and the bower_components symlink.
=> Use package names to import modules and fix lots of typings.

README.md, src/lit-element.ts, src/test/lit-element_test.ts
This shouldn't need to be done from outside the element so it should be protected.
=> Make _requestRender protected

README.md, demo/lit-element.html
=> Add [hidden] convention to example docs

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
I changed most of the Polymer references to lit-element in the CONTRIBUTING.md, but kept some of them in. Please double-check if the language is correct given the new directions.
=> Add GitHub contributing files

README.md
=> Remove fixed known issues

package-lock.json, package.json, rollup.config.js
Was not properly bundling lit-html.
=> Fix npm run checksize

README.md
=> Clarify a few things in the documentation

src/demo/ts-element.ts, src/lib/decorators.ts, src/lib/updating-element.ts, src/lit-element.ts, src/test/lib/decorators_test.ts, src/test/lit-element_styling_test.ts, src/test/lit-element_test.ts, src/test/test-helpers.ts
=> Export decorators

src/demo/ts-element.ts, src/lib/updating-element.ts, src/lit-element.ts, src/test/lib/decorators_test.ts, src/test/lit-element_styling_test.ts, src/test/lit-element_test.ts, src/test/test-helpers.ts
=> Update code with `npm run format`

README.md
=> Update external samples

demo/lit-element.html
=> Fix old API in demo.

README.md
The [awesome list](https://github.com/web-padawan/awesome-lit-html) for lit-html has been approved in sindresorhus/awesome#1357
Please consider adding this badge, so as we could help more people with blog posts, tools etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/lit-element/243)
=> Add awesome-lit-html badge [skip ci]

docs/_layouts/default.html
=> Analytics by default

docs/try/properties.md
The value is a copy/paste from the block above (_Declare a property_)
=> [docs] Fix property initialization in properties doc

CHANGELOG.md, src/lib/decorators.ts
=> Update decorator types

docs/_guide/try.md, docs/_includes/projects/try/events/after/my-element.js, docs/_includes/projects/try/events/before/my-element.js, docs/_includes/projects/try/logic/after/my-element.js, docs/_includes/projects/try/logic/before/my-element.js, docs/_includes/projects/try/style/after/my-element.js, docs/_includes/projects/try/style/before/my-element.js
=> Update try for feedback

docs/css/main.css
=> Updated latest main.css

package.json
=> Add `files` property in the package.json

docs/_guide/start.md
Fixes https://github.com/Polymer/lit-element/issues/404
=> typo in start.md

CHANGELOG.md, package-lock.json, src/env.d.ts, src/lib/decorators.ts
=> Fix decorator types causing compiler errors for TypeScript users.

CHANGELOG.md
=> prepare for 0.7.1 release

CHANGELOG.md
=> Update CHANGELOG for rc3 release.

CHANGELOG.md, src/lib/updating-element.ts, src/lit-element.ts, src/test/lit-element_styling_test.ts
=> Fix inheriting styles from a superclass

docs/_config.yml, docs/_guide/index.md, docs/_includes/topnav.html, docs/_layouts/guide.html, docs/_layouts/try.html, docs/_try/index.md, docs/css/main.css
Preview https://20190130t151327-dot-polymer-lit-element.appspot.com
=> Highlight active link in side nav

docs/_layouts/guide.html
=> Remove pre-release disclaimers

docs/_guide/properties.md
=> [docs] Fix missing anchor

docs/_guide/lifecycle.md
=> broken templates link

docs/_guide/lifecycle.md
=> broken properties link

CHANGELOG.md
=> [skip ci] Prepare for 2.0 release

CHANGELOG.md, package-lock.json, package.json, src/lit-element.ts
=> Use lit-html 1.0

docs/_includes/projects/index-typescript/index.html, docs/_includes/projects/index-typescript/index.ts, docs/_includes/projects/index-typescript/manifest.json, docs/_includes/projects/index-typescript/simple-greeting.ts, docs/_includes/projects/index/index.html, docs/_includes/projects/index/index.ts, docs/_includes/projects/index/manifest.json, docs/_includes/projects/index/simple-greeting.js, docs/index.md, docs/src/stack-blitz.js
* Rename custom-greeting to simple-greeting
* Tweak caption text and formatting of sample
=> [docs] Last-minute tweaks to home page

docs/_guide/styles.md
=> [docs] Spelling Mistake: changed "tern" to "term"

docs/_includes/projects/properties/defaultconverter/my-element.js
Update use of Object.assign on Arrays
=> Update use of Object.assign on Arrays

docs/css/main.css, docs/css/theme.css
=> Sync stylesheet; Place anchors below header

docs/_guide/styles.md
PR for https://github.com/Polymer/lit-element/issues/584
=> change syntax for static styles so that polymer-cli supports it

docs/_guide/templates.md, docs/_includes/projects/docs/templates/compose/my-page.js
refs: #572 
This seems like a quick copy/paste error, but if there was a different approach that this was trying to outline, I'd be happy to alter this PR to support.
=> Remove `static` from composable getters,

package.json
This will make it so npm will link to the homepage and GitHub instead of GitHub twice.
=> Add homepage URL to package.json

package-lock.json, package.json
=> Add `np` for releases

docs/_guide/publish.md
=> Docs publish decorators plugin fix

docs/_guide/styles.md
=> Fix broken anchors and links to them

docs/_try/create.md
=> Remove obsolete link

docs/_guide/lifecycle.md
=> Added section about custom element lifecycles.

docs/README.md
=> Adapt Arthur's lit-html README for lit-element

docs/_guide/events.md
=> fix events example

docs/_guide/lifecycle.md
=> Add the missing bracket for the "performUpdate" example

docs/_api/api-readme.md, docs/_guide/start.md, docs/_guide/use.md, docs/api/index.html
Had couple of free minutes, not much but hope it helps 😄 
Fixes #531
=> Remove unnecessary --save flag from npm commands

docs/_guide/use.md
Fixed a formatting issue in use.md
=> Fix formatting in use.md

docs/_guide/lifecycle.md
I spent a little more than 1 hour today to solve this, I know this is obvious, but sometimes we don't remember...
Fixes #647
=> Add important information into lifecycle section of docs

docs/_guide/lifecycle.md, src/lib/updating-element.ts
Fixes https://github.com/Polymer/lit-element/issues/746
=> Document _getUpdateComplete in LitElement docs

docs/README.md
@aomarks Adding deployment instructions per our conversation. Would you take a look?
... I included a CLI instruction for migrating traffic, although maybe it would be simpler (if a little slower) to simply re-run the deploy command with `-- --promote`...
=> Add deployment instructions

docs/_guide/events.md
=> Fix event handling docs

docs/_data/guide.yml, docs/_guide/community.md, docs/_layouts/default.html
Fixes #687.
Staged at: https://community-page-dot-polymer-lit-element.appspot.com
=> Add community page for SEO.

docs/_guide/styles.md
=> Fixed typo

.travis.yml
=> Fix Travis tests?

src/lib/decorators.ts
=> Update Constructor type to fix #217

docs/_includes/projects/properties/defaultconverter/my-element.js
=> [Docs] Fixed typo #736

.github/CODEOWNERS
... so I get autoassigned to review docs PRs.
=> Add arthurevans as /docs/ codeowner

docs/_guide/community.md, docs/_layouts/default.html
Staged: https://20190925t102540-dot-polymer-lit-element.appspot.com
=> Update slack invite link.

README.md
A badge in README could be a lot more discoverable than existing icon in the website footer 🙂 
So please consider adding it here.
=> Add the Slack badge to README for discoverability

docs/_data/guide.yml, docs/_layouts/guide.html, docs/css/main.css
PoC for proposed changes to left-nav. Adds left-nav "headers." Also adds a visible marker for the selected section (It's otherwise only identified by color).
Staged: https://left-nav-improvements-dot-polymer-lit-element.appspot.com/guide/templates
=> Add divisions to left nav.

src/lib/decorators.ts
Fixed https://github.com/Polymer/lit-element/issues/863.
=> Correct closure annotation in decorators.

docs/_guide/styles.md
Fixes https://github.com/Polymer/lit-element/issues/924
=> Correct docs: styles - CSS inheritance

CHANGELOG.md
=> Fix formatting of new decorator for consistency

CHANGELOG.md, package-lock.json, package.json, src/lit-element.ts
I don't have the full release process paged in, but I know this is an important step!
=> Prepare for release of v2.3.1

docs/_layouts/try.html
=> Remove obsolete disclaimer.

CHANGELOG.md
=> Added @internalProperty to Changelog

src/lit-element.ts
Noticed this after merging the previous PR, natch.
=> Fix typo & formatting.

docs/_includes/projects/properties/accessorssubclassing/sub-element.js
=> docs: rename reflectToAttribute to reflect

docs/_guide/lifecycle.md
As discussed on polymer slack, I gave it a shot and documented some common use cases.
I decided to use strong emphasis (bold) in the list to make it easily scannable.
Fixes #912
=> Document common use cases for lifecycle

docs/css/main.css, docs/index.md
Staged: https://20200603t165824-dot-polymer-lit-element.uk.r.appspot.com
=> Add BLM banner

src/lib/render-light.ts
Related lit-ssr test PR: https://github.com/PolymerLabs/lit-ssr/pull/60
=> Fix renderLight to call part.setValue

src/lib/decorators.ts, src/test/lib/decorators_test.ts
Forgot to format when merging: https://github.com/Polymer/lit-element/pull/1032
=> Quick re-format.

docs/_data/guide.yml, docs/_guide/build.md, docs/_guide/start.md
Staged: https://build-for-production-dot-polymer-lit-element.uk.r.appspot.com/guide/build
Keeping open for feedback until Friday Aug 7.
Also fixes #1039
=> Add Build for production doc.

CHANGELOG.md, package-lock.json, package.json, src/lit-element.ts
This includes type: module and removes the browserstack badge
=> Prep 2.4.0-pre.3

docs/_guide/start.md
Just a small typo fix I found while reading the getting started :)
=> Fix typo in getting started guide

docs/_guide/events.md
=> Fix small typo

package-lock.json, package.json, src/lib/updating-element.ts, src/lit-element.ts, src/test/lib/updating-element_test.ts, src/test/lit-element_test.ts
Fixes #1126 by addressing a few misc typing issues.
=> Upgrade to TypeScript 4.x

src/lib/decorators.ts, src/test/lib/decorators_test.ts
=> Fix cached query decorator (#1142)

docs/_guide/start.md
Quick, one-liner change updating a broken link to the Open WC's project generator
Fixes #1159
=> Update broken link to open-wc generator

src/lib/decorators.ts
=> Also export `internalProperty` as `state`

CHANGELOG.md, src/lit-element.ts
=> Export UpdatingElement as ReactiveElement

CHANGELOG.md, package-lock.json, package.json, src/lit-element.ts
=> Prepare 2.5.1 release
